[package]
name = "lachesis"
version = "0.1.0"
authors = ["Michele Federici (@ps1dr3x) <michele@federici.tech>"]
edition = "2018"

[dependencies]
easy_reader = "=0.3.1"
serde = "=1.0.80"
serde_json = "=1.0.33"
serde_derive = "=1.0.80"
regex = "=1.0.0"
unindent = "=0.1.3"
semver = "=0.9.0"
tokio = "=0.1.11"
hyper = "=0.12.14"
hyper-tls = "=0.3.0"
futures = "=0.1.25"
indicatif = "=0.10.1"

[dependencies.rusqlite]
version = "=0.15.0"
features = ["bundled"]