[package]
name = "lachesis"
version = "0.1.0"
authors = ["Michele Federici (@ps1dr3x) <michele@federici.tech>"]

[dependencies]
easy_reader = "^0.1.1"
serde = "^1.0"
serde_json = "^1.0"
serde_derive = "^1.0"
reqwest = "^0.8.5"
regex = "^0.2"
unindent = "^0.1.3"
semver = "^0.9.0"
hyper = "^0.12"
hyper-tls = "^0.3.0"
futures = "*"

[dependencies.rusqlite]
version = "0.13.0"
features = ["bundled"]